import imgFirst from "./img/image1.jpg";
import imgSecond from "./img/image29.png";
import imgThird from "./img/3.png";
import imgFour from "./img/4.png";
import imgFive from "./img/5.png";
const cards = [
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 1,
    priceTotal: 998,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 2,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 549,
    count: 1,
    id: 3,
    priceTotal: 549,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 699,
    count: 1,
    id: 4,
    priceTotal: 699,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 5,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 6,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 31,
    priceTotal: 998,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 32,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 549,
    count: 1,
    id: 33,
    priceTotal: 549,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 699,
    count: 1,
    id: 34,
    priceTotal: 699,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 35,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 36,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 37,
    priceTotal: 998,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 38,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 549,
    count: 1,
    id: 39,
    priceTotal: 549,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 699,
    count: 1,
    id: 40,
    priceTotal: 699,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 41,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 42,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 43,
    priceTotal: 998,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 44,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 549,
    count: 1,
    id: 45,
    priceTotal: 549,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 699,
    count: 1,
    id: 46,
    priceTotal: 699,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 47,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 48,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 49,
    priceTotal: 998,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 50,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 549,
    count: 1,
    id: 51,
    priceTotal: 549,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 699,
    count: 1,
    id: 52,
    priceTotal: 699,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 53,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 54,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 55,
    priceTotal: 998,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 56,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 549,
    count: 1,
    id: 57,
    priceTotal: 549,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 699,
    count: 1,
    id: 58,
    priceTotal: 699,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 59,
    priceTotal: 499,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 700,
    newSales: 499,
    count: 1,
    id: 60,
    priceTotal: 499,
  },
];

export { cards };
