import imgFirst from "./img/custom1.png";
import imgSecond from "./img/custom2.png";
import imgThird from "./img/custom3.png";
import imgFour from "./img/custom4.png";
import imgFive from "./img/custom5.png";

const castomBuilds = [
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 7,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 8,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 9,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 10,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 11,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 61,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 62,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 63,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 64,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 65,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 66,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 67,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 68,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 69,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 70,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 71,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 72,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 73,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 74,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 75,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 76,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 77,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 78,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 79,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 80,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 81,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 82,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 83,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 84,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 85,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 86,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 87,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 88,
  },
  {
    inStock: "in stock",
    img: imgFour,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 89,
  },
  {
    inStock: "in stock",
    img: imgFive,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 90,
  },
];

export { castomBuilds };
