import imgFirst from "./img/descktop1.png";
import imgSecond from "./img/descktop2.jpg";
import imgThird from "./img/descktop3.png";

const desktops = [
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 91,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id:92,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 93,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 94,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 95,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 96,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 97,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 98,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 99,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 100,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 101,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 102,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 103,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 104,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 105,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 106,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 107,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 108,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 109,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 110,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 111,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 112,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 113,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 114,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 115,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 116,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 117,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 118,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 119,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 120,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 121,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 122,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 123,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 124,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 499,
    count: 1,
    id: 125,
  },
];

export { desktops };
