import imgFirst from "./img/monitor1.png";
import imgSecond from "./img/monitor2.png";
import imgThird from "./img/monitor3.png";

const monitors = [
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 800,
    newSales: 468,
    count: 1,
    id: 22,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 600,
    newSales: 499,
    count: 1,
    id: 23,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 230,
    count: 1,
    id: 24,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 300,
    count: 1,
    id: 25,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 389,
    count: 1,
    id: 26,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 800,
    newSales: 468,
    count: 1,
    id: 156,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 600,
    newSales: 499,
    count: 1,
    id: 157,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 230,
    count: 1,
    id: 158,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 300,
    count: 1,
    id: 159,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 389,
    count: 1,
    id: 160,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 800,
    newSales: 468,
    count: 1,
    id: 161,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 600,
    newSales: 499,
    count: 1,
    id: 162,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 230,
    count: 1,
    id: 163,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 300,
    count: 1,
    id: 164,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 389,
    count: 1,
    id: 165,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 800,
    newSales: 468,
    count: 1,
    id: 166,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 600,
    newSales: 499,
    count: 1,
    id: 167,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 230,
    count: 1,
    id: 168,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 300,
    count: 1,
    id: 169,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 389,
    count: 1,
    id: 170,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 800,
    newSales: 468,
    count: 1,
    id: 171,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 600,
    newSales: 499,
    count: 1,
    id: 172,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 230,
    count: 1,
    id: 173,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 300,
    count: 1,
    id: 174,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 389,
    count: 1,
    id: 175,
  },
  {
    inStock: "in stock",
    img: imgFirst,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 800,
    newSales: 468,
    count: 1,
    id: 176,
  },

  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 600,
    newSales: 499,
    count: 1,
    id: 177,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 230,
    count: 1,
    id: 178,
  },
  {
    inStock: "in stock",
    img: imgThird,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 300,
    count: 1,
    id: 179,
  },
  {
    inStock: "in stock",
    img: imgSecond,
    desc: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    oldSales: 499,
    newSales: 389,
    count: 1,
    id: 178,
  },
];

export { monitors };
